### ISSUE TITLE
Export Import Kprime doesn't work

### ISSUE THREAD

**Issue by isacsonk** [ethz-let/moodle-qtype_kprime#1]
## how to reproduce

1) create a kprime question in a category
2) export the question from the question bank as moodle xml
3) import the question again 
--> error message appears
![errorimport](https://cloud.githubusercontent.com/assets/7068702/8303945/173ad482-19a2-11e5-9528-572fb7dae606.PNG)
## Requirement

Export/Import from question bank has to work

**Comment by jonlan** [comment]
ok

**Comment by nexterday** [comment]
If working and open, please close the issue

On 25 Jun 2015, at 12:05, jonlan <notifications@github.com<mailto:notifications@github.com>> wrote:

ok
