### ISSUE TITLE
Problems with submission of the quiz

### ISSUE THREAD

**Issue by adpe** [ethz-let/moodle-qtype_kprime#20]
Hello @nexterday 

We have troubles with the kprime plugin on our moodle platform. The problem is, that the field of the array[3] normal should be "NULL" or an decimal input. 

I was looking into the code, but don't found where "INF" is added into the data array to store it on the DB.

Stacktrace (debug info):
![image](https://user-images.githubusercontent.com/9467708/31600934-7ad2e682-b258-11e7-9552-a39dd96c2834.png)
Our setup:
- RHEL CentOS 7.3
- PHP 7.4.x
- Moodle 3.2.5+ (Build: 20170928)

Thanks for your help!
Adrian

**Comment by adpe** [comment]
Hello @nexterday

We found the error because it depends on the "**How questions behave**". As soon as "Interactive with multiple tries" is selected, the error message appears. In this case, can "INF" stand for infinity? ;-)

Here is the feedback from our didactic department (in german):
> Der Fehler ist wohl darauf zurückzuführen, das Kprim die Option "Hinweise bei Mehrfachversuchen" nicht zur Verfügung stellt. Das macht natürlich Sinn, wenn man diesen Fragentyp lediglich bei summativen Tests einsetzt, bei formativen Tests wäre es jedoch wünschenswert, wenn auch Mehrfachversuche zugelassen wären. Vielleicht könntest du mal mit dem Entwickler schauen, ob er etwas machen kann.

Thanks for your efforts!
Adrian

**Comment by nexterday** [comment]
Hello@adpe

You are right, we maybe need to add the retries feedback/hint plus penalty option. I'll check with the online pruefungen department and once I take green light I will add it.

Regarding the final_grade calculation is divided on zero which leads to the INF. The count of the stemorder is zero which has been fixed now. for now the penalty is the default one (usually zero).


You can download the changes now..

Thanks for reporting the issue, and I'll update you early next week once we come to a point whether we should or not add the hint/penalty.

Cheers
