### ISSUE TITLE
App display of the questions with dark mode

### ISSUE THREAD

**Issue by lucaboesch** [ethz-let/moodle-qtype_kprime#27]
The fact that the questions now display in the App is dope!
I noticed that when switched to dark mode, the text of the distractors wasn't visible any more.
Is that maybe because of the hard coded color codes in styles.css? Are those necessary at all?
Best,
Luca

**Comment by Clyxz** [comment]
Hi Luca!
Thank you for your feedback and for this finding! The issue was indeed css-related and the new commit from a few minutes ago fixes this problem with darkmode. This problem also has been fixed for MTF Questiontype.
