### ISSUE TITLE
0 in option causes error on saving

### ISSUE THREAD

**Issue by wolfstettler** [ethz-let/moodle-qtype_kprime#28]
When creating a prim question and entering the digit 0 (zero) into "option 1",  on saving you get the error "You must supply a value here."
Other Moodle question types do not show this behaviour. Could you please change this so 0 is an acceptable option?
Kind regards,
Wolf

**Comment by Clyxz** [comment]
Hello @wolfstettler,
thanks for reporting this issue. I will take a look into it,
best regards,
Martin

**Comment by Clyxz** [comment]
Solved: Fix coming with the next update.
best,
Martin
