### ISSUE TITLE
Task: Change style of feedback fields

### ISSUE THREAD

**Issue by isacsonk** [ethz-let/moodle-qtype_kprime#3]
Change  style of feedback fields.

Requirement: Change  style of feedback fields. For now when you create a kprime question you easily enter the second answer in the feedback field of the first option instead in the field of the second option. To better lead the user, the styles of the fields should be different.
Change style of title and size of feedback editor-field.

1) Smaller font size of the title "feedback", font color: grey
2) Smaller hight of the feedback field
3) more space between the options
![optionsandfeedbacknew](https://cloud.githubusercontent.com/assets/7068702/8524900/24ba3ace-23fe-11e5-9cdd-6fc264be6801.gif)

**Comment by nexterday** [comment]
![question_edit_form](https://cloud.githubusercontent.com/assets/11849700/8565762/de335be2-2558-11e5-9696-301724b5356a.jpg)

**Comment by mgambarara** [comment]
Tested, ok:
The style of the feedback fields is now clearly different. 
Environment:
Google Chrome, Firefox, Safari, Tablet Internet Explorer
