### ISSUE TITLE
When setting a value in the "ID number" field, 'ERROR: column "category" does not exist' is thrown

### ISSUE THREAD

**Issue by lucaboesch** [ethz-let/moodle-qtype_kprime#31]
Hi!
We noted the following:
In https://github.com/ethz-let/moodle-qtype_kprime/blob/7246b8379e010b39550b33afa82e5efe763ee321/edit_kprime_form.php#L463 there is a query for a column category value in the questions table.
That column beginning Moodle 4.0 does not exist any more.

To reproduce:

- In Moodle 4.0 or higher, create a new kprime question.
- Click "Save and continue".
- Enter any ID value in the "ID number" field.
- Click "Save and continue" again.

**Comment by nexterday** [comment]
great catch Luca! its been fixed now. thanks a mil
