### ISSUE TITLE
Fehler "This file should not be manually included by any component."

### ISSUE THREAD

**Issue by ghost** [ethz-let/moodle-qtype_kprime#36]
Guten Tag ,

wir haben mehrere Installationen mit dem Plugin Kprime und MTF. Eine gute Sache, vielen Dank! Beim Test mit Moodle 4.5+ (Testinstallation) ist jedoch nun folgender Fehler aufgetreten: 

_Fehler in der Kodierung gefunden, den nur Programmierer/innen korrigieren können: This file should not be manually included by any component._

Fragen können bearbeitet werden, eine Anzeige (Vorschau oder Kurs) ist nicht möglich. Ist dieses Verhalten bekannt und erscheint weil das Plugin noch nicht für die aktuelle Version freigegeben ist oder besteht das Problem nur bei unserer Testinstallation?

Danke für eurer Feedback

**Comment by nexterday** [comment]
Hallo
Für 4.5, bitte benutz branch MOODLE_405_STABLE

https://github.com/ethz-let/moodle-qtype_kprime/tree/MOODLE_405_STABLE

**Comment by ghost** [comment]
Yeep, danke für den Hinweis, daran lag es! Vielen Dank!
