### ISSUE TITLE
Task: Hint text (place holder) in fields, which only shows in the editor modus.

### ISSUE THREAD

**Issue by isacsonk** [ethz-let/moodle-qtype_kprime#4]
Hint text (place holder) in fields, which only shows in the editor modus.
## Requirement

The hint text in the fields must be recognized as hints, which the user should replace with his own text. Klicking in the field removes the text. The hint text in mandatory fields has to be overwritten. If not an error message will be thrown: “You must supply a value here.” Leaving the hint text in optional fields doesn’t affect the test run modus. That means, hint text will never be shown to a student taking the test.

The layout oft he hint text must be different from normal text: i.e. grey and inside brackets.

![helptextinfield](https://cloud.githubusercontent.com/assets/7068702/8540615/90960816-2487-11e5-823c-8496f4ca7925.gif)

**Comment by nexterday** [comment]
not possible. tinyMCE is 3.5 in moodle. only version 4 is supported.
