### ISSUE TITLE
Task: Change layout of display of corrected kprime question.

### ISSUE THREAD

**Issue by isacsonk** [ethz-let/moodle-qtype_kprime#5]
Change layout of display of corrected kprime question.
## Requirement

Grey ticks and crosses. Line between chosen answers and correction.

![kprimecorrectionsgreyandline](https://cloud.githubusercontent.com/assets/7068702/8540812/3fbd2a30-2489-11e5-8840-8e61a9cff114.gif)
## Remark

If realizing the line takes too much time, implement it without the line.

**Comment by nexterday** [comment]
![feedback grey](https://cloud.githubusercontent.com/assets/11849700/8565798/170b5262-2559-11e5-83c7-8e30b0873cf3.jpg)

**Comment by nexterday** [comment]
![grey](https://cloud.githubusercontent.com/assets/11849700/8567582/e1e5fcb4-2566-11e5-88b4-f5d0a06a8c87.jpg)

**Comment by mgambarara** [comment]
Tested, ok:
Works as wished.
Environment:
Google Chrome, Firefox, Safari, Tablet Internet Explorer

**Comment by nexterday** [comment]
**\* UPDATE ***

![kp_grey](https://cloud.githubusercontent.com/assets/11849700/9245065/325345e8-41a1-11e5-8fe8-3d5572523987.jpg)
