### ISSUE TITLE
Task: Show correct answer in Analysis of response 

### ISSUE THREAD

**Issue by isacsonk** [ethz-let/moodle-qtype_kprime#6]
Task: Show correct answer in Analysis of response 

How to reproduce:
1.   go to an exam which already has been solved
2.  Click on Results -->Statistics 
3.  -->than click on the title of a kprime question
You’ll see the statistics of the question

The problem here is, that as a user, you cannot tell which responses are correct.
## Requirement

If possible implement:
In the column "Model response" add "(correct response)" behind the correct answer.
## Example: 

the sky is blue: True (correct response)
the sky is green: False 
## [No response]

Column Partial credits:
Scoring method subpoints (with max points=1):
4 correct answers -> 1 point
3 correct -> 0.75
2 correct -> 0.5
0 or 1 correct -> 0

For the scoring method “subpoints” each correct answer should have 25%

Scoring method kprime and kprime 1/0 cannot be calculated, if possible put n/a or something like that. If not possible put 0 as it is now.

**Comment by nexterday** [comment]
do you mean as per attached screenshot?

![sample](https://cloud.githubusercontent.com/assets/11849700/8545710/621f153e-24b1-11e5-8f17-bffc6eb0bec8.jpg)

**Comment by isacsonk** [comment]
like this
![statssticsnew](https://cloud.githubusercontent.com/assets/7068702/8547915/38221d74-24c2-11e5-83ac-2b3b3f204e73.gif)

**Comment by nexterday** [comment]
![kprime analysis](https://cloud.githubusercontent.com/assets/11849700/8565802/271741c0-2559-11e5-8699-082de00510dd.jpg)
